### ISSUE TITLE
Code Tingspeak

### ISSUE THREAD

**Issue by LeanderVanBaekel** [Wasknijper/MWD-InternetOfThings#1]
Je code voor Tingspeak kan veel compacter. Voor een voorbeeld kun je even bij raymond kijken: [https://github.com/RaymondKorrel/iot/blob/master/thingspeak/thingspeak.ino](https://github.com/RaymondKorrel/iot/blob/master/thingspeak/thingspeak.ino)

**Comment by Wasknijper** [comment]
Aangepast: https://github.com/Wasknijper/MWD-InternetOfThings/commit/713560f970f36c2c21728b59c3bc77087190ed5b
